#!/usr/bin/env sh

spacebar -m config position           top
spacebar -m config text_font          "Avenir:Heavy:13.0"
spacebar -m config icon_font          "remixicon:Regular:13.0"
spacebar -m config background_color   0xff322B54
spacebar -m config foreground_color   0xffa8a8a8
spacebar -m config space_icon_color   0xff458588
spacebar -m config power_icon_color   0xff4a8fe7
spacebar -m config battery_icon_color 0xff7fb285
spacebar -m config dnd_icon_color     0xffD49FF9
spacebar -m config clock_icon_color   0xffa8a8a8
spacebar -m config space_icon_strip           
spacebar -m config power_icon_strip    
spacebar -m config space_icon         
spacebar -m config clock_icon         
spacebar -m config dnd_icon           
spacebar -m config clock_format       "%d/%m %R"
